[package]
name = "midi-to-wav"
version = "0.0.1"
authors = [ "Ng Guoyou" ]
edition = "2018"

[dependencies]
docopt = "1"
serde = "1.0"
serde_derive = "1.0"

[dependencies.synthrs]
git = "https://github.com/gyng/synthrs"
rev = "77e062f3e40304dd2c3611d70ece6a0e4eaf9750"
